runtime: python310

instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  max_instances: 1

beta_settings:
    cloud_sql_instances: flask-stock-mysql:us-central1:flask-stock-mysql-instance

handlers:
- url: /static
  static_dir: static

env_variables:
  # The following variables are now managed by Secret Manager
  # SECRET_KEY: "..."
  # MYSQL_USER: "..."
  # MYSQL_PASSWORD: "..."
  # MYSQL_DB: "..."

