runtime: python310

instance_class: F1

entrypoint: gunicorn -b :$PORT app:app

automatic_scaling:
  max_instances: 1

handlers:
- url: /static
  static_dir: static

env_variables:
  SECRET_KEY: "f1f32b786e2f34c917094b6d3260cb51b79df55d5241d529" # REPLACE WITH YOUR ACTUAL SECRET KEY
  MYSQL_HOST: "localhost" # REPLACE WITH YOUR CLOUD SQL CONNECTION NAME or IP
  MYSQL_USER: "root" # REPLACE WITH YOUR MYSQL USER
  MYSQL_PASSWORD: "Mytoor@1212" # REPLACE WITH YOUR MYSQL PASSWORD
  MYSQL_DB: "flask_stock_plot_db" # REPLACE WITH YOUR MYSQL DATABASE NAME
